# Generated by Django 2.0 on 2018-01-26 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(whitelist=['unleashed.be'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='expectations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'X')], max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='need_to_know',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture_url',
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
