# Generated by Django 2.0 on 2017-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.TextField(max_length=40),
        ),
    ]
