# Generated by Django 2.0 on 2017-12-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('squad', '0002_auto_20171214_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('squad', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='squad.Squad')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='squademployee',
            unique_together={('employee', 'squad')},
        ),
    ]
