# Generated by Django 2.0 on 2017-12-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SquadEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('squad', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='squads.Squad')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='squademployee',
            unique_together={('employee', 'squad')},
        ),
    ]
