# Generated by Django 2.0 on 2018-02-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Empty', 'Empty'), ('Workspace', 'Workspace')], default='Workspace', max_length=30)),
                ('color', models.CharField(default='FFFFFF', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='floorplan.Room')),
            ],
        ),
    ]
