# Generated by Django 2.0 on 2018-01-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='FFFFF', max_length=8),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(default='Empty', max_length=30),
        ),
        migrations.AddField(
            model_name='space',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='floorplan.Room'),
        ),
        migrations.AlterField(
            model_name='space',
            name='employee_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
