# Generated by Django 2.0 on 2018-01-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Empty', 'Empty'), ('Workspace', 'Workspace')], default='Workspace', max_length=30),
        ),
        migrations.AlterField(
            model_name='space',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
    ]
